"""Generate mod_folder/common/scripted_effects/mltd_ai_frontage_effects.txt - each state's frontage for MLT's AI.

MLT's AI sizes its army by frontage (mltd_ai_survey, common/scripted_effects/mltd_ai_survey_effects.txt). Script cannot see
provinces, so this measures them once from OWB's map: for every state, the land provinces that touch a land province of
another state (map/provinces.bmp, map/definition.csv, history/states), each worth the divisions of 20 width that fill its
terrain's combat width (common/terrain/00_terrain.txt: 80, so 4; tunnel 40, so 2), and the number of states it borders.
The effect mltd_ai_set_state_edges writes them to each state as mltd_ai_edge and mltd_ai_nbs; the survey runs it once a
game, then counts a border state's frontage as mltd_ai_edge x (foreign neighbours / mltd_ai_nbs). Checked against run 3's
save (2281): MLT's 100 true border provinces were 400 full-width divisions, the approximation 343.
Rebuild after an OWB map update. Needs numpy and Pillow.

Usage: python build_ai_frontage.py [--dry]
"""
import glob
import os
import re
import sys
from collections import defaultdict

import numpy as np
from PIL import Image

REPO = os.path.dirname(os.path.abspath(__file__))
OWB = r"C:\Program Files (x86)\Steam\steamapps\workshop\content\394360\2265420196"
OUT = os.path.join(REPO, "mod_folder", "common", "scripted_effects", "mltd_ai_frontage_effects.txt")
DIVISION_WIDTH = 20


def rd(path):
    return open(path, "rb").read().decode("utf-8-sig", errors="replace")


def terrain_widths():
    text = re.sub(r"#[^\n]*", "", rd(os.path.join(OWB, "common", "terrain", "00_terrain.txt")))
    widths, name = {}, None
    for line in text.split("\n"):
        m = re.match(r"^\t([a-z_]+) = \{", line)
        if m:
            name = m.group(1)
        m = re.search(r"\bcombat_width = (\d+)", line)
        if m and name:
            widths[name] = int(m.group(1))
    assert widths.get("plains") == 80, widths
    return widths


def main():
    widths = terrain_widths()
    img = np.array(Image.open(os.path.join(OWB, "map", "provinces.bmp")).convert("RGB"), dtype=np.uint32)
    code = (img[:, :, 0] << 16) | (img[:, :, 1] << 8) | img[:, :, 2]
    colour, land, terrain = {}, set(), {}
    for line in open(os.path.join(OWB, "map", "definition.csv"), encoding="latin-1"):
        p = line.strip().split(";")
        if len(p) >= 7 and p[0].isdigit():
            pid = int(p[0])
            colour[(int(p[1]) << 16) | (int(p[2]) << 8) | int(p[3])] = pid
            terrain[pid] = p[6]
            if p[4] == "land":
                land.add(pid)
    state_of, provinces = {}, {}
    for path in glob.glob(os.path.join(OWB, "history", "states", "*.txt")):
        text = re.sub(r"#[^\n]*", "", rd(path))
        m = re.search(r"\bid\s*=\s*(\d+)", text)
        pm = re.search(r"provinces\s*=\s*\{([^}]*)\}", text)
        if m and pm:
            sid = int(m.group(1))
            provinces[sid] = [int(x) for x in pm.group(1).split() if x.isdigit()]
            for x in provinces[sid]:
                state_of[x] = sid
    touch = defaultdict(set)
    for a, b in ((code[:, :-1], code[:, 1:]), (code[:-1, :], code[1:, :])):
        diff = a != b
        for x, y in set(zip(a[diff].tolist(), b[diff].tolist())):
            pa, pb = colour.get(x), colour.get(y)
            if pa in land and pb in land:
                touch[pa].add(pb)
                touch[pb].add(pa)
    rows = []
    for sid in sorted(provinces):
        edge, neighbours = 0, set()
        for p in provinces[sid]:
            if p not in land:
                continue
            other = {state_of[q] for q in touch.get(p, ()) if state_of.get(q) not in (None, sid)}
            if other:
                edge += widths.get(terrain.get(p), 80) // DIVISION_WIDTH
                neighbours |= other
        if edge:
            rows.append((sid, edge, len(neighbours)))
    out = ["# Rising Tide - MLT's AI: each state's frontage (generated by build_ai_frontage.py - do not edit by hand)",
           "#",
           "# mltd_ai_edge: divisions of %d width that fill the combat width of the state's land provinces touching another state;" % DIVISION_WIDTH,
           "# mltd_ai_nbs: how many states it borders. Written once a game by mltd_ai_survey (mltd_ai_survey_effects.txt), for",
           "# every state that borders another (%d of OWB's). Measured from OWB's map; see the script's docstring." % len(rows),
           "mltd_ai_set_state_edges = {"]
    out += ["\t%d = { set_variable = { mltd_ai_edge = %d } set_variable = { mltd_ai_nbs = %d } }" % r for r in rows]
    out += ["}", ""]
    text = "\n".join(out)
    print("%d states, mean frontage %.1f divisions" % (len(rows), sum(r[1] for r in rows) / len(rows)))
    if "--dry" not in sys.argv:
        open(OUT, "w", encoding="utf-8", newline="\n").write(text)
        print("wrote", OUT)


if __name__ == "__main__":
    main()
